spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaPro
    username: postgres
    password: admin

server:
  port: 8081


integration:
  url: "http://localhost:8080"
  connect-timeout: 1s
  read-timeout: 30s
